### ISSUE TITLE
[internal] github action not running

### ISSUE THREAD

**Issue by lenntt** [apache/incubator-devlake-playground#9]
would it be possible to run this as a required check on PRs?
https://github.com/apache/incubator-devlake-playground/blob/main/.github/workflows/python-check.yml

**Comment by lenntt** [comment]
I see it runs, but it fails: https://github.com/apache/incubator-devlake-playground/actions/runs/8190416615
didn't foresee this restriction, should look into alternatives to abatilo/actions-poetry@v2

**Comment by d4x1** [comment]
I am not sure how to solve it.   In DevLake, it uses a script.
https://github.com/apache/incubator-devlake/blob/main/.github/workflows/test.yml#L51
